/**
 * ai-html-sanitizer.ts
 *
 * Sanitizes and normalizes HTML content generated by AI (Gemini/GPT/etc.)
 * to ensure 100% compatibility with the Tiptap editor schema and all supported marks.
 *
 * Supported marks handled:
 *  - Bold       → <strong>
 *  - Italic     → <em>
 *  - Underline  → <u>
 *  - Strike     → <s>
 *  - Code       → <code>
 *  - Highlight  → <mark>
 *  - Superscript → <sup>
 *  - Subscript  → <sub>
 *  - Link       → <a href="...">
 *
 * Supported nodes handled:
 *  - Headings   → <h1>–<h6>
 *  - Paragraph  → <p>
 *  - LegalNode  → <div data-type="legal-node">
 *  - Blockquote → <blockquote>
 *  - HorizontalRule → <hr>
 */

// ─── 1. Strip Markdown noise the AI might have included ──────────────────────

function stripMarkdownSyntax(html: string): string {
  return html
    // Code fences (```) — must come before ** rules
    .replace(/```[\w]*\n?/g, "")
    .replace(/```/g, "")
    // Inline code `text` → <code>text</code>  (only outside existing HTML tags)
    .replace(/`([^`]+)`/g, "<code>$1</code>")
    // Bold+Italic ***text*** or ___text___ (evitando engolir linhas de assinatura de underline puro)
    .replace(/\*\*\*(.+?)\*\*\*/g, "<strong><em>$1</em></strong>")
    .replace(/___([^\n_]+?)___/g, "<strong><em>$1</em></strong>")
    // Bold **text** or __text__
    .replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>")
    .replace(/__([^\n_]+?)__/g, "<strong>$1</strong>")
    // Italic *text* or _text_  (single, not double)
    .replace(/\*([^*\n]+?)\*/g, "<em>$1</em>")
    .replace(/_([^\n_]+?)_/g, "<em>$1</em>")
    // Strikethrough ~~text~~
    .replace(/~~(.+?)~~/g, "<s>$1</s>")
    // Heading ATX style: ## Title → <h2>Title</h2>
    .replace(/^#{6}\s+(.+)$/gm, "<h6>$1</h6>")
    .replace(/^#{5}\s+(.+)$/gm, "<h5>$1</h5>")
    .replace(/^#{4}\s+(.+)$/gm, "<h4>$1</h4>")
    .replace(/^#{3}\s+(.+)$/gm, "<h3>$1</h3>")
    .replace(/^#{2}\s+(.+)$/gm, "<h2>$1</h2>")
    .replace(/^#{1}\s+(.+)$/gm, "<h1>$1</h1>")
    // Horizontal rule --- or *** (standalone line)
    .replace(/^[-*]{3,}$/gm, "<hr>")
}

// ─── 2. Normalise non-standard HTML tags → Tiptap schema equivalents ─────────

function normaliseTags(html: string): string {
  return html
    // Bold: <b> → <strong>
    .replace(/<b(\s[^>]*)?>([\s\S]+?)<\/b>/gi, "<strong$1>$2</strong>")
    // Italic: <i> → <em>
    .replace(/<i(\s[^>]*)?>([\s\S]+?)<\/i>/gi, "<em$1>$2</em>")
    // Strikethrough: <del> / <strike> → <s>
    .replace(/<del(\s[^>]*)?>([\s\S]+?)<\/del>/gi, "<s$1>$2</s>")
    .replace(/<strike(\s[^>]*)?>([\s\S]+?)<\/strike>/gi, "<s$1>$2</s>")
    // Underline: already <u>, keep it — Tiptap Underline extension parses it
    // Highlight: <mark> — Tiptap Highlight extension parses it
    // Remove <span> wrappers that carry NO useful attribute (pure noise)
    .replace(/<span>([\s\S]+?)<\/span>/gi, "$1")
    // Keep <span style="..."> — TextStyle extension may use it for colour
}

// ─── 3. Remove completely disallowed tags (strip tag but keep inner text) ─────

const DISALLOWED_TAGS = [
  "script", "style", "iframe", "object", "embed", "form",
  "input", "button", "select", "textarea", "nav", "footer",
  "header", "aside", "figure", "figcaption", "template", "svg",
  "table", "thead", "tbody", "tr", "td", "th",   // tables via TableKit instead
]

function removeDisallowedTags(html: string): string {
  let result = html
  for (const tag of DISALLOWED_TAGS) {
    // Self-closing variant
    result = result.replace(new RegExp(`<${tag}\\s*\\/?>`, "gi"), "")
    // Paired variant — strip tags but keep inner content
    result = result.replace(new RegExp(`<${tag}(\\s[^>]*)?>([\\s\\S]*?)<\\/${tag}>`, "gi"), "$2")
  }
  return result
}

// ─── 4. Remove dangerous / noisy attributes ───────────────────────────────────

function sanitiseAttributes(html: string): string {
  return html
    // Remove event handlers (onclick, onmouseover, etc.)
    .replace(/\s+on\w+="[^"]*"/gi, "")
    .replace(/\s+on\w+='[^']*'/gi, "")
    // Remove javascript: href
    .replace(/href="javascript:[^"]*"/gi, 'href="#"')
    // Remove data-* except Tiptap-specific ones we need
    .replace(/\s+data-(?!type|level|text-align|background|node-id|id|ai-highlight)[a-z-]+=["'][^"']*["']/gi, "")
    // Remove class attributes from inline elements (let Tiptap handle styling)
    .replace(/(<(?:strong|em|s|u|code|mark|sup|sub|a)\b[^>]*)\s+class="[^"]*"/gi, "$1")
}

// ─── 5. Structural cleanup ────────────────────────────────────────────────────

function cleanupStructure(html: string): string {
  return html
    // Remove full document scaffolding the AI might have returned
    .replace(/<!DOCTYPE[^>]*>/gi, "")
    .replace(/<html[^>]*>/gi, "").replace(/<\/html>/gi, "")
    .replace(/<head[\s\S]*?<\/head>/gi, "")
    .replace(/<body[^>]*>/gi, "").replace(/<\/body>/gi, "")
    // Collapse multiple <br> into one
    .replace(/(<br\s*\/?>\s*){2,}/gi, "<br>")
    // Remove empty paragraphs
    .replace(/<p[^>]*>\s*<\/p>/gi, "")
    // Remove empty legal nodes
    .replace(/<div[^>]*data-type="legal-node"[^>]*>\s*<\/div>/gi, "")
    // Collapse 3+ consecutive newlines
    .replace(/\n{3,}/g, "\n\n")
    .trim()
}

// ─── 6. Streaming safety guard ────────────────────────────────────────────────
// During streaming, the HTML may be incomplete. These patterns signal an
// incomplete fragment that should NOT be inserted yet.

export function isIncompleteHtmlFragment(html: string): boolean {
  const trimmed = html.trimEnd()
  // Ends mid-tag
  if (trimmed.endsWith("<") || trimmed.endsWith("</")) return true
  // Ends with an open tag with no closing >
  if (/<[a-zA-Z][^>]*$/.test(trimmed)) return true
  return false
}

// ─── 7. Public API ────────────────────────────────────────────────────────────

/**
 * Full sanitization pipeline for AI-generated HTML.
 * Safe to call on each streaming chunk.
 */
export function sanitiseAiHtml(rawHtml: string): string {
  let html = rawHtml

  // Step 1 — strip stray markdown
  html = stripMarkdownSyntax(html)
  // Step 2 — normalise non-standard HTML tags
  html = normaliseTags(html)
  // Step 3 — remove disallowed tags (keep inner text)
  html = removeDisallowedTags(html)
  // Step 4 — strip dangerous/noisy attributes
  html = sanitiseAttributes(html)
  // Step 5 — structural cleanup
  html = cleanupStructure(html)

  return html
}

/**
 * Lightweight variant for use during streaming — skips expensive operations
 * that may corrupt partial HTML fragments.
 */
export function sanitiseAiHtmlStream(rawHtml: string): string {
  let html = rawHtml

  // Only apply safe, non-destructive passes during streaming
  html = html
    .replace(/```html\s?/gi, "")
    .replace(/```\s?/gi, "")
    .replace(/<!DOCTYPE.*?>/gi, "")
    .replace(/<html>/gi, "").replace(/<\/html>/gi, "")
    .replace(/<body>/gi, "").replace(/<\/body>/gi, "")
    .replace(/(<br\s*\/?>\s*){2,}/gi, "<br>")
    .replace(/<p>\s*<\/p>/gi, "")
    .trim()

  return html
}
